# Generated by Django 5.0.3 on 2024-03-21 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRNS_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_Number', models.CharField(max_length=100)),
                ('MM_YY', models.CharField(max_length=50)),
                ('CVV', models.CharField(max_length=50)),
                ('Name_on_the_card', models.CharField(max_length=50)),
                ('Amount', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
